"""Render readable tables from measured values; never replace missing FPS with zero."""
from pathlib import Path
import json

HERE = Path(__file__).resolve().parent
data = json.loads((HERE/'PERFORMANCE.json').read_text())['runs']
lines = ['# #132 measured workload and presentation', '',
         'Generated by render_measurements.py. Method and qualifications: [RESULTS.md](RESULTS.md).', '',
         '## Natural arrival and the isolated cap control', '',
         '| Run | Alive range | Tics/s | Displayed FPS mean | Median / p95 / p99 interval (ms) | Coverage |',
         '| --- | --- | ---: | ---: | --- | ---: |']

def row(label, v):
    d = v['display']
    fps = f"{d['mean_fps']:.2f}" if d['n'] else 'unavailable'
    intervals = ' / '.join(f'{d[k]:.2f}' for k in ['median_ms','p95_ms','p99_ms']) if d['n'] else 'unavailable'
    alive = '-'.join(str(int(x)) for x in v['alive_range'])
    return f"| {label} | {alive} | {v['tics_per_second']:.2f} | {fps} | {intervals} | {v['display_covered_wall_pct']:.1f}% |"

for name in ['baseline-natural-a','baseline-natural-b','staged-natural-a','cap-natural-a','cap-natural-b']:
    if name in data:
        lines.append(row(name, data[name]['phases']['arrival']))
lines += ['', '## Foreground controls (tics 700-1050)', '',
          'The author reserved foreground time; the game was activated before this settled window.',
          'Same camera 0, settings, production AI and no scripted deaths; cap setup is compressed.',
          'These are short controls (ten simulation seconds), not a replacement for full-route tails.', '',
          '| Run | Alive range | Tics/s | Displayed FPS mean | Median / p95 / p99 interval (ms) | Coverage |',
          '| --- | --- | ---: | ---: | --- | ---: |']
for name in ['focus-full-a','focus-cap-a']:
    if name in data:
        lines.append(row(name, data[name]['foreground_settled']))
lines += ['', 'cap-natural-a has partial presentation coverage. cap-natural-b is its complete repeat.',
          'The cap controls start at 2,000 through diagnostic compressed setup; natural buildup does not.', '',
          '## Complete-budget diagnostic by simulation phase', '',
          '| Run / phase | Alive range | Tics/s | Displayed FPS mean | Median / p95 / p99 interval (ms) | Coverage |',
          '| --- | --- | ---: | ---: | --- | ---: |']
for name in ['baseline-long-a','staged-long-a','staged-long-b']:
    if name not in data:
        continue
    for phase, v in data[name]['phases'].items():
        lines.append(row(name+' / '+phase, v))
lines += ['', 'Phase tics: arrival 35-3500; buildup 3500-6650; sustained 6650-14000;',
          'budget 14000-20650; late 20650-22750; decline 22750-24850.',
          'The baseline loses its living Mandingas before tic 5,075. Its later FPS measure a corpse field,',
          'not a still-living full army. Do not interpret later baseline/staged ratios as equal-load speedups.', '',
          '## Camera sensitivity', '',
          '| Run / camera segment | Alive range | Tics/s | Displayed FPS mean | Median / p95 / p99 interval (ms) | Coverage |',
          '| --- | --- | ---: | ---: | --- | ---: |']
for name in ['baseline-natural-b','staged-natural-a','cap-natural-b','staged-long-b']:
    if name not in data:
        continue
    for segment, v in data[name]['views'].items():
        if name != 'staged-long-b' or int(segment) >= 12:
            lines.append(row(name+' / '+segment+' (view '+str(v['view'])+')', v))
lines += ['', '## Spawning and retained corpses', '']
for name in ['staged-long-a','staged-long-b']:
    if name not in data:
        continue
    r = data[name]
    lines.append(f"- {name}: final successful {int(r['last']['total'])}, remaining {int(r['last']['remaining'])}, "
                 f"maximum living {int(r['max_alive'])}, maximum corpses {int(r['max_corpses'])}, "
                 f"maximum pending sampled {int(r['max_pending'])}; final scripted deaths {int(r['last']['scriptedDeaths'])}.")
    windows = [v for v in r['spawn_windows'] if v['display']['n']]
    if windows:
        worst = max(windows, key=lambda v:v['display']['worst_ms'])
        lines.append(f"- {name}: {len(windows)} spawn windows excluding screenshot/bench/camera opportunities; "
                     f"worst observed display gap {worst['display']['worst_ms']:.2f} ms in tics "
                     f"{int(worst['start_tic'])}-{int(worst['end_tic'])}. This is coincidence with a spawn window, "
                     'not exclusive timing of the spawning function; combat/collision/thermal work continues.')

profile_path = HERE/'PROFILE_RESULTS.json'
if profile_path.exists():
    profiles = json.loads(profile_path.read_text())
    names = {0:'CombatActor.Tick',1:'Native Tick + state dispatch',2:'Collision callback',3:'Contact latch',
             4:'Combat health effects',5:'Offensive statistics',6:'Resource pulse',7:'Resource activity check',
             9:'Siege pulse',10:'Attacker target',11:'Command election',13:'Target refresh',14:'Crew refill',
             15:'Gun orders',16:'Cannon target',17:'Walk command',18:'Port Tick',20:'Machine guards',
             21:'Cannon Tick',22:'Cannon projectile',23:'Player Tick',24:'Elemental status',
             27:'Actor projectile',28:'Simple elemental projectile',29:'Reinforcement living census',
             30:'Reinforcement placement',31:'Reinforcement Tick',32:'NPC thermal step',
             33:'Thermal advance',34:'Thermal environment sample',35:'Thermal integration'}
    lines += ['', '## Isolated sampled subsystem costs', '',
              'Each instrumented package samples every 37th tic. Initialization tic 0 is excluded.',
              'Exclusive time subtracts only instrumented children; unwrapped children remain attributed',
              'to their parent. Native Tick includes native movement and state actions, not physics alone.',
              'These runs are diagnostic overhead controls, not FPS comparisons. Sparse batch placement',
              'can be missed by sampling; absence here is not evidence of zero spawn cost.', '']
    for name, r in profiles.items():
        lines += [f"### {name} ({r['sampled_tics']} sampled tics)", '',
                  '| Component | Inclusive ms / sampled tic | Exclusive ms / sampled tic | Calls |',
                  '| --- | ---: | ---: | ---: |']
        for c in sorted(r['categories'], key=lambda x:x['exclusive_ms_per_sample_tic'], reverse=True):
            if c['calls']:
                lines.append(f"| {names.get(c['id'],str(c['id']))} | {c['inclusive_ms_per_sample_tic']:.4f} | "
                             f"{c['exclusive_ms_per_sample_tic']:.4f} | {int(c['calls'])} |")
lines += ['', 'Native rendering CPU samples: individual *-bench.txt files, indexed by BENCHMARKS.json.',
          'PresentMon GPU-busy distributions and one-second TPS tails remain in PERFORMANCE.json.',
          'Raw worst gaps include measurement commands and the explicitly labelled late save.', '']
(HERE/'MEASUREMENTS.md').write_text('\n'.join(lines), encoding='utf-8')
print('Rendered measurement tables for', len(data), 'completed runs.')
