"""Read-only baseline checks plus two deterministic rebuilds of owned outputs."""
from pathlib import Path
import argparse,hashlib,json,subprocess,sys
ROOT=Path(__file__).resolve().parents[2]
HERE=Path(__file__).resolve().parent
BASE='abd4f578a698cefc72e91d5176c79458276e6115'

def digest(data):return hashlib.sha256(data).hexdigest()
def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output',default='GENERATORS.json',help='Evidence filename inside this validation directory')
    args=parser.parse_args()
    if Path(args.output).name!=args.output:raise SystemExit('Output must be a filename, not a path.')
    if 'gzdoom.exe' in subprocess.check_output(['tasklist','/FI','IMAGENAME eq gzdoom.exe','/NH'],text=True).lower():
        raise SystemExit('Finish native runs before generator verification.')
    paths=['src/graphics/caelum/shotgun.textures','assets/source/art/shotgun_517/REGISTRATION.json',
           'src/maps/MAP02.wad','src/caelum/world/CaelumMazeLayout.zs','assets/map02_maze/MAP02_MANIFEST.json']
    def hashes():return {p:digest((ROOT/p).read_bytes()) for p in paths}
    before=hashes();runs=[]
    for _ in range(2):
        for script in ['register_shotgun.py','generate_map02_maze.py']:
            subprocess.run([sys.executable,str(ROOT/'assets/generators'/script)],cwd=ROOT,check=True,capture_output=True)
        runs.append(hashes())
    assert before==runs[0]==runs[1], 'Generated bytes changed; investigate before accepting.'
    old=json.loads(subprocess.check_output(['git','show',BASE+':assets/map02_maze/MAP02_MANIFEST.json'],cwd=ROOT))
    new=json.loads((ROOT/'assets/map02_maze/MAP02_MANIFEST.json').read_text())
    old_drops={d['tid']:d for d in old['drops']};new_drops={d['tid']:d for d in new['drops']}
    assert all(new_drops[k]==v for k,v in old_drops.items()),'Existing supply assignment changed.'
    added=[d for k,d in new_drops.items() if k not in old_drops]
    assert len(added)==6 and all(d['cls']=='CaelumShotgunAmmo' and d['amount']==20 for d in added)
    assert [sum(d['zone']==z for d in added) for z in range(4)]==[2,1,2,1]
    old_wad=subprocess.check_output(['git','show',BASE+':src/maps/MAP02.wad'],cwd=ROOT)
    assert digest(old_wad)==before['src/maps/MAP02.wad'],'MAP02 geometry changed.'
    provenance=json.loads((ROOT/'assets/source/art/shotgun_517/PROMPTS.json').read_text(encoding='utf-8'))
    art={}
    for runtime,source in provenance['selected_runtime_sources'].items():
        src=(ROOT/'assets/source/art/shotgun_517'/source).read_bytes()
        dst=(ROOT/'src/graphics/caelum/shotgun'/runtime).read_bytes()
        assert src==dst
        art[runtime]=digest(src)
    result={'base':BASE,'deterministic_runs':2,'generated':before,'selected_art_sha256':art,
            'existing_drops_preserved':len(old_drops),'new_drops':added,'map02_geometry_unchanged':True}
    (HERE/args.output).write_text(json.dumps(result,indent=2)+'\n',encoding='utf-8')
    print(json.dumps({'deterministic_runs':2,'existing_drops_preserved':len(old_drops),'new_stacks':len(added),'cartridges':120,'map02_geometry_unchanged':True}))
if __name__=='__main__':main()
