"""Register untouched original VFX atlases and deterministic cosmetic data (#137)."""
from pathlib import Path
import json, shutil, hashlib
from register_carbine_world import rgba,alpha_bounds

ROOT=Path(__file__).resolve().parents[2]
SOURCE=ROOT/'assets/source/art/elemental_518'
OUT=ROOT/'src/graphics/caelum/vfx'

def main():
    data=json.loads((SOURCE/'DESIGN.json').read_text())
    OUT.mkdir(parents=True,exist_ok=True)
    lines=['// Generated by register_elemental_vfx.py; original PNGs remain unchanged.']
    frames=[]
    for name,prefixes,size in [('projectiles',data['projectile_prefixes'],data['projectile_size']),('statuses',data['status_prefixes'],data['status_size'])]:
        path=SOURCE/(name+'.png');w,h,rows=rgba(path)
        shutil.copyfile(path,OUT/path.name)
        columns=data[name+'_columns'];row_cuts=data[name+'_rows']
        assert len(columns)==5 and columns[0]==0 and columns[-1]==w
        assert len(row_cuts)==len(prefixes)+1 and row_cuts[0]==0 and row_cuts[-1]==h
        for row,prefix in enumerate(prefixes):
            y1,y2=row_cuts[row:row+2]
            bounds=[alpha_bounds(rows,(columns[i],y1,columns[i+1],y2)) for i in range(4)]
            visible_width=max(b[2]-b[0]+1 for b in bounds)
            visible_height=max(b[3]-b[1]+1 for b in bounds)
            for phase in range(4):
                x1,x2=columns[phase:phase+2]
                cw,ch=x2-x1,y2-y1
                sprite=f'{prefix}{chr(65+phase)}0'
                pivot=ch//2 if name=='projectiles' else max(b[3] for b in bounds)-y1+1
                sx=cw/size[0] if name=='projectiles' else visible_width/size[0]
                sy=ch/size[1] if name=='projectiles' else visible_height/size[1]
                lines.append(f'Sprite "{sprite}", {cw}, {ch} {{ XScale {sx:.9f} YScale {sy:.9f} Offset {cw//2}, {pivot} Patch "graphics/caelum/vfx/{name}.png", {-x1}, {-y1} }}')
                frames.append({'name':sprite,'clip':[x1,y1,x2,y2],'pivot':[cw//2,pivot]})
    (OUT/'elemental.textures').write_text('\n'.join(lines)+'\n',encoding='utf-8')
    zs=['// Datos cosméticos generados desde DESIGN.json; sin valores de combate.', 'class CaelumElementalVFXData : Object {']
    for key in ['frame_tics','particle_life','trail_interval','dense_trail_interval','detail_distance','dense_detail_distance','impact_tics']:
        zs.append(f' const {key.upper()}={data[key]};')
    for name,typ,values in [('SpriteName','String',data['projectile_prefixes']),('Tint','Color',data['colors']),('LightRadius','int',data['light_radii']),('StatusSprite','String',data['status_prefixes'])]:
        zs.append(f' static {typ} {name}(int kind) {{ switch(kind) {{')
        for i,v in enumerate(values):
            value=str(v) if isinstance(v,int) else ('0x'+v if typ=='Color' else '"'+v+'"')
            zs.append(f' case {i}:return {value};')
        zs.append(' } return '+('0;' if typ in ['int','Color'] else '"VFFR";')+' }')
    zs.extend(['}', '// Registro nativo de cada frame: GetSpriteIndex no crea sprites.', 'class CaelumElementalVFXFrames : Actor { States { Spawn: TNT1 A -1; Stop; Frames:'])
    for p in data['projectile_prefixes']+data['status_prefixes']:zs.append(f' {p} ABCD 1 Bright;')
    zs.append(' Stop; } }')
    target=ROOT/'src/caelum/actors/CaelumElementalVFXData.zs'
    target.write_text('\n'.join(zs)+'\n',encoding='utf-8')
    manifest={'frames':frames,'sha256':{p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted(OUT.glob('*'))}}
    (SOURCE/'REGISTRATION.json').write_text(json.dumps(manifest,indent=2)+'\n',encoding='utf-8')
    print('Registered 52 original VFX frames and shared cosmetic data.')

if __name__=='__main__':main()
